### PR TITLE
allows use of minikube config for cpus/memory

### LINKED ISSUE #248: Support user minikube config for memory / cpu
Currently we've [hardcoded](https://github.com/knative-sandbox/kn-plugin-quickstart/blob/main/pkg/minikube/minikube.go#L176) the CPUs required by minikube. And we do not set memory at all.

We should check the user's minikube config to see if values for cpus / memory are set (`minikube config get cpus [or] memory`). If the value exists, we should use that when creating the cluster.

If it does not exist, we should default to 3 GB memory and 3 CPUs.

### PR DESCRIPTION
**Pull request by psschwei**
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>

Fixes #248 

**Release Note**

```release-note
Quickstart will use system values for `memory` and `cpus` if specified in `minikube config`. If not specified, will default to 3GB / 3 cpus
```

/assign @csantanapr

### CODE REVIEW

**Comment by mapleeit** [comment]
Can we make a new release that contains this feature? 

I'm trying to write a GitHub Actions for knative quickstart to help people setup knative in GitHub Actions Runner. So that we can have e2e test based on that.

**Comment by psschwei** [comment]
v1.4 is [scheduled to be out on April 19](https://github.com/knative/release#schedule)

**Comment by csantanapr** [comment]
@psschwei 
Could we cherry pick this to the branch release-1.3?
So there are binaries available, other alternative is just compile it from main branch in the GitHub action or compile your own and saved it some where it can be fetched

**Comment by psschwei** [comment]
The 1.3.2 release (with this change in it) should come out on Tuesday

**Comment by csantanapr** [comment]
Great thanks @psschwei

**Pull request merged**
