### PR TITLE
update to latest knative 0.24

### LINKED ISSUE #57: update to install latest version of knative 0.24
- Update version from 0.23 to 0.24
- Print versions being installed for kourier, serving, eventing
/assign

### PR DESCRIPTION
**Pull request by csantanapr**
# Changes
- :gift: Update to knative 0.24

/kind feature

Fixes #57 

**Release Note**
```release-note
- :gift: Update to knative 0.24
```

### CODE REVIEW

**Comment by csantanapr** [comment]
/hold

It looks like version 0.24 has problems installing kourier step.

Running `kn-quickstart`
```
namespace/kourier-system created
serviceaccount/3scale-kourier created
clusterrole.rbac.authorization.k8s.io/3scale-kourier created
clusterrolebinding.rbac.authorization.k8s.io/3scale-kourier created
deployment.apps/3scale-kourier-control created
service/kourier-control created
deployment.apps/3scale-kourier-gateway created
service/kourier created
service/kourier-internal created
Error from server (InternalError): error when creating "https://github.com/knative-sandbox/net-kourier/releases/download/v0.24.0/kourier.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": dial tcp 10.96.242.3:443: connect: connection refused
Error from server (InternalError): error when creating "https://github.com/knative-sandbox/net-kourier/releases/download/v0.24.0/kourier.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": dial tcp 10.96.242.3:443: connect: connection refused
```
fails on first attempt to install kourier.yaml

This works on konk, since konk tries twice on every yaml apply here https://github.com/csantanapr/knative-kind/blob/master/02-kourier.sh#L10

/assign @psschwei

**Comment by csantanapr** [comment]
It looks like I was able to reproduce on both 0.23 and 0.24, but in 0.24 it looks like the webhook takes longer to be ready

To reproduce run the following

With 0.24
````
kubectl apply -f https://github.com/knative/serving/releases/download/v0.24.0/serving-crds.yaml
kubectl wait --for=condition=Established --all crd
kubectl apply -f https://github.com/knative/serving/releases/download/v0.24.0/serving-core.yaml
kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n knative-serving
kubectl apply -f https://github.com/knative-sandbox/net-kourier/releases/download/v0.24.0/kourier.yaml
````

with 0.23
````
kubectl apply -f https://github.com/knative/serving/releases/download/v0.23.0/serving-crds.yaml
kubectl wait --for=condition=Established --all crd
kubectl apply -f https://github.com/knative/serving/releases/download/v0.23.0/serving-core.yaml
kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n knative-serving
kubectl apply -f https://github.com/knative-sandbox/net-kourier/releases/download/v0.23.0/kourier.yaml
```

```
pod/activator-67656dcbbb-mz7x6 condition met
pod/autoscaler-df6856b64-d4ckp condition met
pod/controller-788796f49d-xwsgq condition met
pod/domain-mapping-65f58c79dc-zgtzj condition met
pod/domainmapping-webhook-cc646465c-vlhc7 condition met
pod/webhook-859796bc7-rwn2f condition met
namespace/kourier-system created
serviceaccount/3scale-kourier created
clusterrole.rbac.authorization.k8s.io/3scale-kourier created
clusterrolebinding.rbac.authorization.k8s.io/3scale-kourier created
deployment.apps/3scale-kourier-control created
service/kourier-control created
deployment.apps/3scale-kourier-gateway created
service/kourier created
service/kourier-internal created
Error from server (InternalError): error when creating "https://github.com/knative-sandbox/net-kourier/releases/download/v0.24.0/kourier.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": dial tcp 10.96.75.68:443: connect: connection refused
Error from server (InternalError): error when creating "https://github.com/knative-sandbox/net-kourier/releases/download/v0.24.0/kourier.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": dial tcp 10.96.75.68:443: connect: connection refused
```

**Comment by csantanapr** [comment]
@psschwei I opened an issue in serving for someone to take a look at the webhook problem.
In the mean time could you implement the logic I use in konk, to retry once if the kubectly apply fails, on the second attempt after sleeping for 5 seconds seems to always work in konk

**Comment by csantanapr** [comment]
With the retries that @psschwei put in place now I can't reproduce the problem kourier install

**Review by psschwei — APPROVED** [review]
/lgtm

**Pull request merged**
