### PR TITLE
Kind cluster install options

### LINKED ISSUE #16: Add functionality to check Kind version, delete/recreate existing Kind cluster
The KonK script currently checks to ensure that users have a sufficiently up-to-date version of Kind installed (see [here](https://github.com/csantanapr/knative-kind/blob/master/01-kind.sh#L11-L22)).

It also gives users the option of deleting and recreating a Knative cluster if one already exists (see [here](https://github.com/csantanapr/knative-kind/blob/master/01-kind.sh#L25-L34)).

We should implement similar functionality in this plugin.

### PR DESCRIPTION
**Pull request by psschwei**
# Changes

- Validates Kind version; if older version found, prompts user to update before continuing
- Provides option to delete/recreate existing Kind cluster (or to continue with existing cluster)

/kind enhancement

Fixes #16 

**Release Note**

```release-note
Provides some Kind management options via the quickstart plugin
```

/assign @julz @csantanapr

### CODE REVIEW

**Comment by psschwei** [comment]
Will need to rebase this after #24 merges
/hold

**Comment by csantanapr** [comment]
@psschwei you need to rebase this now

**Comment by csantanapr** [comment]
tested on macos
```
❯ ./kn-quickstart kind
Running Knative Quickstart using Kind
Kind version is: kind v0.11.0 go1.16.4 darwin/amd64

knative

Knative Cluster kind-knative already installed.
Delete and recreate [y/N]: y
deleting cluster...
Creating Kind cluster...
    Waiting on cluster to be ready...
Cluster created
Starting Knative Serving install...
    CRDs installed...
    Core installed...
Finished installing Knative Serving
Starting Networking layer install...
    Kourier installed...
    Ingress patched...
    Kourier service installed...
    Domain DNS set up...
Finished installing Networking layer
Starting Knative Eventing install...
    CRDs installed...
    Core installed...
    In-memory channel installed...
    Mt-channel broker installed...
```
/lgtm
/approve

**Pull request merged**
